datos = [
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Álvaro Obregón"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Azcapotzalco"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Benito Juárez"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Coyoacán"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Cuajimalpa de Morelos"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Cuauhtémoc"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Gustavo A. Madero"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Iztacalco"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Iztapalapa"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "La Magdalena Contreras"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Miguel Hidalgo"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Milpa Alta"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Tláhuac"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Tlalpan"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Venustiano Carranza"},
    {"pais": "México", "estado_provincia": "Ciudad de México", "municipio": "Xochimilco"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Acambay de Ruiz Castañeda"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Acolman"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Aculco de Espinoza"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Almoloya de Alquisiras"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Almoloya de Juárez"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Almoloya del Río"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Amanalco"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Amatepec"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Amecameca"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Apaxco"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Atenco"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Atizapán de Zaragoza"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Toluca"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Tlalnepantla de Baz"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Tultepec"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Tultitlán"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Valle de Chalco Solidaridad"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Villa del Carbón"},
    {"pais": "México", "estado_provincia": "Estado de México", "municipio": "Zumpango"},
    {"pais": "México", "estado_provincia": "Quintana Roo", "municipio": "Benito Juárez"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Abasolo"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Agualeguas"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Aldamas"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Allende"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Anáhuac"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Apodaca"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Aramberri"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Burgos"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Bustamante"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Cadereyta Jiménez"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "China"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Ciénega de Flores"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Doctor González"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Galeana"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Garcia"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "General Bravo"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "General Escobedo"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "General Terán"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "General Treviño"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "General Zaragoza"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "General Zuazua"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Guadalupe"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Higueras"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Hualahuises"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Lampazos de Naranjo"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Linares"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Marín"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Mártires de la Concordia"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Matamoros"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Monterrey"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Parás"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Pesquería"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Los Ramones"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Rayones"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Sabinas Hidalgo"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Salinas Victoria"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "San Nicolás de los Garza"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "San Pedro Garza García"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Santa Catarina"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Santiago"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Vallecillo"},
    {"pais": "México", "estado_provincia": "Nuevo León", "municipio": "Villaldama"},
    {"pais": "México", "estado_provincia": "Estado De México", "municipio": "Chicoloapan"},
    {"pais": "México", "estado_provincia": "Estado De México", "municipio": "Texcoco"},
]
